version: 2.1

jobs:
  test-lint-build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run:
          name: test
          command: cargo test
      - run:
          name: lint
          command: cargo clippy
      - run:
          name: build
          command: cargo build

  publish:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run:
          name: publish
          command: cargo publish

workflows:
  test:
    jobs:
      - test-lint-build:
          filters:
            branches:
              ignore:
                - master

  deploy:
    jobs:
      - test-lint-build:
          filters:
            branches:
              only:
                - master

      - publish:
          requires:
            - test-lint-build
          filters:
            branches:
              only:
                - master
