version: 2.1

orbs:
  rust: circleci/rust@1.6.0

workflows:
  test:
    jobs:
      - rust/lint-test-build:
          release: true
          version: 1.60.0
          filters:
            branches:
              ignore:
                - master
